<template>
  <transition name="fade">
    <div v-if="visible" class="dialog-overlay" @click.self="close">
      <div class="dialog">
        <h3 style="margin-bottom: 0.5rem; text-align: center">❤️ 完美！</h3>

        <!-- Form inputs -->
        <label for="title">Title:</label>
        <input
          v-model="title"
          id="title"
          type="text"
          placeholder="Give a cool name"
          @keydown="(event: Event) => event.stopPropagation()"
        />

        <label for="description">Description:</label>
        <textarea
          v-model="description"
          id="description"
          placeholder="Say something about it"
          @keydown="(event: Event) => event.stopPropagation()"
        ></textarea>

        <!-- Buttons -->
        <div class="button-group">
          <button @click="submitForm" class="submit-btn">Submit</button>
          <button @click="close" class="cancel-btn">Cancel</button>
        </div>
      </div>
    </div>
  </transition>
</template>

<script setup lang="ts">
import type { DialogInput } from '@/types';
import { ref, defineEmits } from 'vue';

/** This component is generated by ChatGPT */

// Refs to bind form inputs
const visible = ref(false);
const title = ref('');
const description = ref('');

// Define the submit event
const emit = defineEmits<{
  (event: 'submit', data: DialogInput): void;
}>();

// Function to open the dialog
const open = () => {
  visible.value = true;
};

defineExpose({
  open
});

// Function to close the dialog
const close = () => {
  visible.value = false;
  resetForm();
};

// Function to reset the form fields
const resetForm = () => {
  title.value = '';
  description.value = '';
};

// Function to handle form submission
const submitForm = () => {
  const data: DialogInput = {
    title: title.value === '' ? '-' : title.value,
    description: description.value
  };
  emit('submit', data);
  close(); // Close dialog after submitting
};
</script>

<style scoped>
.dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.dialog {
  background: white;
  padding: 20px;
  border-radius: 5px;
  width: 300px;
  max-width: 90%;
}

.label {
  display: block;
  margin: 5px 0;
}

input,
textarea {
  width: 100%;
  padding: 8px;
  margin-bottom: 10px;
}

.button-group {
  display: flex;
  justify-content: space-between;
}

.submit-btn,
.cancel-btn {
  padding: 8px 15px;
  cursor: pointer;
}

.submit-btn {
  background-color: rgba(0, 0, 0, 0.78);
  border: solid 2px rgba(0, 0, 0, 0.78);
  color: white;
}

.cancel-btn {
  background-color: white;
  border: solid 2px rgba(0, 0, 0, 0.78);
  color: black;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
