<template>
  <transition name="fade">
    <div v-if="visible" class="dialog-overlay" @click.self="close">
      <div class="dialog">
        <h3
          v-if="recordedNotes && recordedNotes.length > 2"
          style="margin-bottom: 0.5rem; text-align: center"
        >
          ❤️ 完美！
        </h3>
        <div v-else style="margin-bottom: 0.5rem; text-align: center">
          😇 Please make more than 2 notes
        </div>

        <!-- Form inputs -->
        <label for="title">Title:</label>
        <input
          v-model="title"
          id="title"
          type="text"
          placeholder="Name for your masterpiece"
          :disabled="recordedNotes && recordedNotes.length <= 2"
          @keydown="(event: Event) => event.stopPropagation()"
        />

        <label for="description">Description:</label>
        <textarea
          v-model="description"
          id="description"
          placeholder="Say something about it"
          :disabled="recordedNotes && recordedNotes.length <= 2"
          @keydown="(event: Event) => event.stopPropagation()"
        ></textarea>

        <!-- Buttons -->
        <div class="button-group">
          <button
            :disabled="recordedNotes && recordedNotes.length <= 2"
            @click="submitForm"
            class="submit-btn"
          >
            Submit
          </button>
          <button @click="close" class="cancel-btn">Cancel</button>
        </div>
      </div>
    </div>
  </transition>
</template>

<script setup lang="ts">
import type { DialogInput, RecordedNote } from '@/types';
import { ref } from 'vue';

/** This component is generated by ChatGPT */

// Refs to bind form inputs
const visible = ref(false);
const title = ref('');
const description = ref('');

// Define the props
defineProps<{
  recordedNotes: RecordedNote[] | undefined;
}>();

// Define the submit event
const emit = defineEmits<{
  (event: 'submit', data: DialogInput): void;
}>();

// Function to open the dialog
const open = () => {
  visible.value = true;
};

defineExpose({
  open
});

// Function to close the dialog
const close = () => {
  visible.value = false;
  resetForm();
};

// Function to reset the form fields
const resetForm = () => {
  title.value = '';
  description.value = '';
};

// Function to handle form submission
const submitForm = () => {
  const data: DialogInput = {
    title: title.value === '' ? '-' : title.value,
    description: description.value
  };
  emit('submit', data);
  close(); // Close dialog after submitting
};
</script>

<style scoped>
.dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(26, 26, 46, 0.4);
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  display: flex;
  justify-content: center;
  align-items: center;
}

.dialog {
  background: var(--bg-card);
  padding: var(--space-5);
  border-radius: var(--radius-lg);
  width: 320px;
  max-width: 90%;
  box-shadow: var(--shadow-lg);
}

label {
  display: block;
  margin-bottom: var(--space-1);
  font-size: 0.8125rem;
  font-weight: 500;
  letter-spacing: 0.02em;
  color: var(--text-secondary);
}

input,
textarea {
  width: 100%;
  padding: var(--space-2) var(--space-3);
  margin-bottom: var(--space-3);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  background: var(--penguin-white);
  font-family: inherit;
  font-size: 0.875rem;
  color: var(--text-primary);
  outline: none;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
}

input:focus,
textarea:focus {
  border-color: var(--penguin-black);
  box-shadow: 0 0 0 2px rgba(26, 26, 46, 0.08);
}

input:disabled,
textarea:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

textarea {
  resize: vertical;
  min-height: 60px;
}

.button-group {
  display: flex;
  justify-content: flex-end;
  gap: var(--space-2);
  user-select: none;
  margin-top: var(--space-2);
}

.submit-btn,
.cancel-btn {
  padding: var(--space-2) var(--space-4);
  cursor: pointer;
  border-radius: var(--radius-md);
  font-family: inherit;
  font-size: 0.875rem;
  font-weight: 500;
  transition: all 0.15s ease;
}

.submit-btn {
  background-color: var(--penguin-black);
  border: 2px solid var(--penguin-black);
  color: white;
}

.submit-btn:hover:not(:disabled) {
  opacity: 0.85;
  transform: translateY(-1px);
}

.submit-btn:disabled {
  background-color: var(--border);
  border-color: var(--border);
  color: var(--text-secondary);
  cursor: not-allowed;
  transform: none;
}

.cancel-btn {
  background-color: transparent;
  border: 2px solid var(--border);
  color: var(--text-primary);
}

.cancel-btn:hover {
  border-color: var(--penguin-black);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.25s ease;
}

.fade-enter-active .dialog,
.fade-leave-active .dialog {
  transition: opacity 0.25s ease, transform 0.25s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.fade-enter-from .dialog {
  transform: translateY(8px);
}
</style>
